// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelCompany.Web.Data;

namespace TravelCompany.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200420181501_NewBD")]
    partial class NewBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelCompany.Web.Data.Entities.ExpensesEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<double>("ExpenseTotal");

                    b.Property<int?>("Expenseid");

                    b.Property<string>("Photo");

                    b.Property<int?>("Travelid");

                    b.HasKey("id");

                    b.HasIndex("Expenseid");

                    b.HasIndex("Travelid");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("TravelCompany.Web.Data.Entities.ExpensesTypeEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExpensesType");
                });

            modelBuilder.Entity("TravelCompany.Web.Data.Entities.TravelEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Document")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("VisitReason")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("Travel");
                });

            modelBuilder.Entity("TravelCompany.Web.Data.Entities.ExpensesEntity", b =>
                {
                    b.HasOne("TravelCompany.Web.Data.Entities.ExpensesTypeEntity", "Expense")
                        .WithMany("Expenses")
                        .HasForeignKey("Expenseid");

                    b.HasOne("TravelCompany.Web.Data.Entities.TravelEntity", "Travel")
                        .WithMany("Expense")
                        .HasForeignKey("Travelid");
                });
#pragma warning restore 612, 618
        }
    }
}
